### ISSUE TITLE
Dutch (nl_BE) makes domogik crash at startup

### ISSUE THREAD

**Issue by jschaeke** [domogik/domogik-brain-core#4]
pi@raspberrypi:/opt/dmg/domogik-brain-base $ cat /var/log/domogik/core_butler.log
2017-02-19 21:05:23,342 domogik-butler ERROR Error accessing packages directory : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/bin/butler.py", line 393, in load_brain_parts
    self.brain.load_directory(lang_dir)
  File "/opt/dmg/domogik/src/domogik/butler/rivescript/rivescript/rivescript.py", line 211, in load_directory
    self.load_file(os.path.join(directory, item))
  File "/opt/dmg/domogik/src/domogik/butler/rivescript/rivescript/rivescript.py", line 223, in load_file
    self._parse(filename, lines)
  File "/opt/dmg/domogik/src/domogik/butler/rivescript/rivescript/rivescript.py", line 321, in _parse
    raise Exception(syntax_error)
Exception: Syntax error in /var/lib/domogik//domogik_packages/brain_base/rs/nl_BE/DT_Humidity.rive line 4: Triggers can't contain uppercase letters, backslashes or dots in UTF-8 mode. (near: + Wat is de vochtigheid voor *)
. You should create it
2017-02-19 21:05:33,376 domogik-butler ERROR Error while getting the devices list over MQ. Error is : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/bin/butler.py", line 210, in reload_devices
    str_devices = cli.request('dbmgr', msg.get(), timeout=10).get()[1]
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by jschaeke** [comment]
https://github.com/domogik/domogik-brain-base/pull/5/commits

**Comment by jschaeke** [comment]
the prq above will make it start, but I'll need to revise it further.. the butler answers now like:
`Ik begrijp het niet<call>star</call>` 
  --> should not display and speak `<call>star</call>` 
I quickly compared star.rive it against the french version, seems the dutch files has redundant of those call-tags. 
eg  
`RESPONSES = [u"Ik begrijp het niet<call>star</call>",
                 u"Wat bedoel je ?<call>star</call>"]`
vs
`RESPONSES = [u"Je n'ai pas compris",
                 u"Pouvez-vous reformuler ?"]`

Is the dutch version still actively maintained? @Cereal2nd have you used nl_BE lately?

**Comment by fritz-smh** [comment]
On my side, I don't maintain the dutch version actively. If you cant to handle it, feel free to open new PR, I will be more prompt to merge them (it seems I missed the emails... it was during vacation days)
